development:
  adapter: postgresql
  encoding: unicode
  database: digren_development
  pool: 5
  username: josemiguelcansado
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: digren_test
  pool: 5
  username: josemiguelcansado
  password: